name: Metrics
on:
  # Ejecuta el workflow diariamente a la medianoche UTC
  schedule:
    - cron: "0 0 * * *"
  # (Opcional) Permite ejecutar el workflow manualmente
  workflow_dispatch:
  # (Opcional) Ejecuta el workflow al hacer push a la rama principal
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
