# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Lines of Code Changed
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  code-lines-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          filename: assets/metrics.plugin.code.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Ruubia
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_skipped: testing, The-Futurists_Manthan_Frontend
          plugin_lines_repositories_limit: 4