# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Ruubia
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Atlantic/Canary
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_repositories: yes
          plugin_featured_repositories_repositories: 
          - "Ruubia/exercise-postcard"
          - "Ruubia/Instagram-Photo-Feed-con-HTML-CSS"
          - "Ruubia/Post-de-Instagram"
          - "Ruubia/Instagram-Feed-con-Bootstrap"
          - "Ruubia/Crea-un-formulario-con-HTML5"
          - "Ruubia/exercise-collaborative-html-website"
          - "Ruubia/Generador-de-excusas-en-JS"
          - "Ruubia/Generador-de-Nombres-de-Dominios"
          - "Ruubia/Conditional-Profile-Card-Generator"
          - "Ruubia/Random-Card-Generator"
          - "Ruubia/exercise-unit-test-with-jest"
          - "Ruubia/Landing-Page-con-React"
          - "Ruubia/Todolist-App-Using-React"
